<?php $scales = $this->product_model->M_get_product_scale_assoc(); ?>
<ul class="list-group">
    <li class="list-group-item active">CSV Format Documentation</li>
    <li class="list-group-item">
        <strong>Columnn (id): </strong>A unique id is automatically generated by <?php echo $this->session->userdata('pos_hoster_cmp') ?> for all products. 
        Dont change this id if you are updating products.
        Leave Blank if your importing new products.
    </li>
    <li class="list-group-item">
        <strong>Columnn (handle): </strong> *A human prefered ID for the product. This field is to be unique for every product but common for VARIANTS or BLEND product. Maximum characters - 40. The Field is Required.
    </li>
    <li class="list-group-item">
        <strong>Columnn (product_name): </strong> The name of your product. Maximum characters - 40. The Field is Required.
    </li>
    <li class="list-group-item">
        <strong>Column (SKU): </strong> 
        Stock keeping unit, a Universal Product Code(UPC) or Own Product barcodes. Please note this field must be unique and should not repeat for any other products.
        "KILO" scale selling products inherit their own barcodes respective to weight/length/litre, irrespective to SKU/UPC defined. 
        Note that the sku does'nt start with "KILO" scale barcode prefix. The Field is Required.
    </li>
    <li class="list-group-item">
		<ul class="list-group">
            <li class="list-group-item active">Column (product_scale): </li>
            <?php
            $i=0;
            foreach($scales as $key => $value) {
            ?>
                <li class="list-group-item">"<?php echo $key?>" - If Product sold <?php echo $value ?></li>
            <?php $i++; } ?>     
            <li class="list-group-item">
                Key in any of the above scales without quotes(*Note CAPS, Case Sensitive). Other scales not allowed. If then, row is dropped. The field is required.
            </li>       
		</ul>
    </li>
    <li class="list-group-item">
        <strong>Column (outlet_locale_tax_{outlet_name}): </strong>Type tax name(check spell & ensure you have configured taxes correctly) or leave blank to associate product to outlet locale tax. Check the outlet name is proper in your header field.
    </li>
    <li class="list-group-item">
        <strong>Column (description): </strong>Your description says how the product is displayed for internal staffing and online cart. Can be left blank if not required 
    </li>
    <li class="list-group-item">
        <strong>Column (supplier_name):</strong> Key in the name of the supllier(check spells) or leave blank in case of multiple/no suppliers for this product
    </li>
    <li class="list-group-item">
        <strong>Column (product_category): </strong>Category of the product belongs to. Check whether you have configured categories earlier. Leave blank to void categorization. 
    </li>
    <li class="list-group-item">
        <strong>Column (product_brand): </strong>Brand of the product belongs to. Check whether you have configured brands earlier. Leave blank to void branding. 
    </li>
    <li class="list-group-item">
        <strong>Column (product_tag): </strong>Semicolon(";") seperated products tags to categorize/search this product. Type existing(spell sensitive) or new tags. <br>*Eg: Shirt, T-Shirt, Lion Logo shirt, Yellow T-shirt etc.. for product IPL CSK Jersey
    </li>
    <li class="list-group-item">
        <strong>Column (supplier_or_operated_price):</strong> The cost at which the product is purchased from the supplier or it its operated cost to build.
    </li>
    <li class="list-group-item">
        <strong>Column (retail_price):</strong> The cost at which the product is sold to the customer.
    </li>
    <li class="list-group-item">
        <strong>Column (warehouse_id):</strong> The product warehouse id for internal accounting.
    </li>
    <li class="list-group-item">
        <strong>Column (prurchase_id):</strong> The product purchase id (during order to suppliers) for internal accounting.
    </li>    
    <li class="list-group-item">
        <?php
        $num_array = array(1 => 'one',2 => 'two',3 => 'three');
        $var_array = array(
                        array('Small or Red or male'),
                        array('Small or Green or Male'),
                        array('Small or Red or Female'),
                        array('Large or Green or Male'),
                        );
        ?>
		<ul class="list-group">
            <li class="list-group-item text-muted small active">
                <strong>Column (variant_*) </strong> - This fields are only for products that has variants. 
                Leave blank if your product has no variants, else follow the example. 
                Please check that the product_name is common, handle(common, without spaces, check spelling) is same for the variants you are associating and "product_scale" column set to "VARIANTS".
            </li>
			<?php for($i=1;$i<=3;$i++){ ?>
            <li class="list-group-item"><b>Column (variant_<?php echo $num_array[$i]?>_name</b> => Variant name) &rarr; Egs: SIZE or COLOUR or GENDER</li>
            <li class="list-group-item"><b>Column (variant_<?php echo $num_array[$i]?>_value</b> => Variant value) &rarr; Egs: <?php echo $var_array[$i][0]?></li>
            <?php } ?>
            <li class="list-group-item">
	            <h4>Example</h4>
                <div class="table-responsive small">
                    <table class="table table-condensed table-striped table-curved">
                        <thead>
                        <tr>
                            <th>handle</th>
                            <th>product_name</th>
                            <th>sku</th>
                            <th>product_scale</th>
                            <th>variant_one_name</th>
                            <th>variant_one_value</th>
                            <th>variant_two_name</th>
                            <th>variant_two_value</th>
                            <th>variant_three_name</th>
                            <th>variant_three_value</th>
                        </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>T-shirt</td>
                                <td>T-shirt</td>
                                <td>10001</td>
                                <td>VARIANTS</td>
                                <td>Size</td>
                                <td>Small</td>
                                <td>Colour</td>
                                <td>Red</td>
                                <td>Gender</td>
                                <td>Male</td>
                            </tr>
                            <tr>
                                <td>T-shirt</td>
                                <td>T-shirt</td>
                                <td>10002</td>
                                <td>VARIANTS</td>
                                <td>Size</td>
                                <td>Small</td>
                                <td>Colour</td>
                                <td>Red</td>
                                <td>Gender</td>
                                <td>Female</td>
                            </tr>
                            <tr>
                                <td>T-shirt</td>
                                <td>T-shirt</td>
                                <td>10003</td>
                                <td>VARIANTS</td>
                                <td>Size</td>
                                <td>Medium</td>
                                <td>Colour</td>
                                <td>Red</td>
                                <td>Gender</td>
                                <td>Male</td>
                            </tr>
                            <tr>
                                <td>T-shirt</td>
                                <td>T-shirt</td>
                                <td>10004</td>
                                <td>VARIANTS</td>
                                <td>Size</td>
                                <td>Medium</td>
                                <td>Colour</td>
                                <td>Red</td>
                                <td>Gender</td>
                                <td>Female</td>
                            </tr>
                            <tr><td colspan="10">... and so on</td></tr>
                        </tbody>
                    </table>
				</div>
            </li>            
		</ul>
    </li>
    <li class="list-group-item">
        <ul class="list-group">
            <li class="list-group-item active small">
                <strong>Column (associate_*) </strong> - This fields are only for products that are sold as group.
                Skip fields if your product is not sold on group, else follow the example. 
                Please check that the product_name is common, handle(common, without spaces, check spelling) is same for the products you are associating and "product_scale" column set to "BLEND".
            </li>            
            <li class="list-group-item">
                <strong>Column (associate_SKU): </strong> For Grouping or blending Products, type the associated product SKU. *<smal>Check associated product SKU's are placed/saved earlier</smal>
            </li>
            <li class="list-group-item">
                <strong>Column (associate_quantity): </strong> Associated product's quantity(can be fractional upto 3 decimal places).
            </li>
            <li class="list-group-item">
	            <h4>Example</h4>
                <div class="table-responsive small">
                    <table class="table table-condensed table-striped table-curved">
						<thead>
                        	<tr>
                            	<th>handle</th>
                            	<th>product_name</th>
                            	<th>sku</th>
                            	<th>product_scale</th>
                            	<th>associate_sku</th>
                            	<th>associate_quantity</th>
                            </tr>
                        </thead>
                        <tbody>
                        	<tr>
                            	<td>chickensandwich</td>
                            	<td>Chicken Sandwich</td>
                            	<td>1005</td>
                            	<td>BLEND</td>
                            	<td></td>
                            	<td></td>                                
                            </tr>
                        	<tr>
                            	<td>chickensandwich</td>
                            	<td>Chicken Sandwich</td>
                            	<td>1005</td>
                            	<td>BLEND</td>
                            	<td>1002 (say onion)</td>
                            	<td>0.01 (10gms of a weighing scale product)</td>                                
                            </tr>
                        	<tr>
                            	<td>chickensandwich</td>
                            	<td>Chicken Sandwich</td>
                            	<td>1005</td>
                            	<td>BLEND</td>
                            	<td>1003 (say tomato)</td>
                            	<td>0.01 (10gms of a weighing scale product)</td>                                
                            </tr>
                        	<tr>
                            	<td>chickensandwich</td>
                            	<td>Chicken Sandwich</td>
                            	<td>1005</td>
                            	<td>BLEND</td>
                            	<td>1004 (say 2 bread slice)</td>
                            	<td>0.02 (20gms of a weighing scale product)</td>                                
                            </tr>
                            <tr>
                            	<td colspan="6">... and so on ...</td>
                            </tr>
                        </tbody>
					</table>
                    <ul class="list-group">
                        <li class="list-group-item">Bracket values for info only</li>
                    	<li class="list-group-item">Leave inventory_*, reorder_*, restock_* fields empty.</li>
                    </ul>
				</div>                    
            </li>
        </ul>
	</li>    
    <li class="list-group-item">
        <strong>Column (loyalty_value): </strong> Check you have enabled <?php echo anchor(base_url().'setup/loyalty','Customer Loyalty','class="btn btn-xs btn-primary"') ?> to true. If yes key in the loyalty ratio value (100:1 format) of the retail price else type your own custom price or 0.
    </li>
    <li class="list-group-item">
        <strong>Column (product_weight): </strong> Weight of the Product(Kg) including Packing. Weighed during Shipment. The Field is Required and Numeric.
    </li>
    <li class="list-group-item">
        <strong>Column (trace_inventory): </strong> To enable this product to affect your inventory type 1 else 0.
    </li>
    <li class="list-group-item">
        <strong>Column (show_in_shopping_cart): </strong> To enable this product to show in shopping cart integration, type 1 else 0.
    </li>
    <li class="list-group-item">
        <strong>Column (shipping): </strong> To enable or disable shipping for this product. To enable, type 1 else 0.
    </li>
    <li class="list-group-item">
        <strong>Column (visiblity): </strong> To enable this product to sale, type 1 else 0.
    </li>
    <li class="list-group-item">
        <strong>Column (inventory_{outlet_name}): </strong> Stock Qty of the product for corresponding outlet to be sold. Inventory tracking steps down qty during sales. Check the outlet name is proper in your header field. The field is required and numeric.
    </li>
    <li class="list-group-item">
        <strong>Column (reorder_{outlet_name}): </strong> The product is brought to <?php echo anchor(base_url().'inventory/stock_order','Stock Order','class="btn btn-xs btn-primary"') ?> automatically for corresponding outlet when stock decreases to "n" reorder level. Check your outlet name is proper in your header field. The field is required and numeric.
    </li>
    <li class="list-group-item">
        <strong>Column (restock_{outlet_name}): </strong> The product is brought to <?php echo anchor(base_url().'inventory/stock_order','Stock Order','class="btn btn-xs btn-primary"') ?> automatically for corresponding outlet for quantum of stock to be ordered. Check your outlet name is proper in your header field. The field is required and numeric.
    </li>
</ul>
<ul class="list-group">
    <li class="list-group-item active">Note</li>
    <li class="list-group-item">Rows and headers with non latin or foreign characters are dropped. Dont worry, you can change them later after upload.</li> 
    <li class="list-group-item">Get set & have a flashy upload.</li> 
</ul>
