<ul class="list-group">
	<li class="list-group-item active"><h4>CSV Format Documentation</h4></li>
    <li class="list-group-item">
        <strong>Columnn (id): </strong>A unique id is automatically generated by <?php echo $this->session->userdata('pos_hoster_cmp') ?> for new customers. 
        Dont change this id if you are updating customers.
        Leave Blank if your importing new customers.
	</li>
    <li class="list-group-item">
        <strong>Column (customer_name): </strong> The name of your customer. Maximum characters - 25. The Field is Required and it cant be empty.
    </li>
    <li class="list-group-item">
        <strong>Column (group_name): </strong> Type the name of the group else leave blank to add them to "General Customer" group. If misspelled "General Customer" group is considered.
    </li>
    <li class="list-group-item">
        <strong>Column (customer_code): </strong> Type your customer code else leave blank, so that we can create one for you.
    </li>
    <li class="list-group-item">
        <strong>Column (company_name): </strong> The Company for which he/she working for.
    </li>
    <li class="list-group-item">
        <strong>Column (cust_dob): </strong> The date of birth of the customer. Leave blank if not available.
    </li>
    <li class="list-group-item">
        <strong>Column (cust_anniversary): </strong> Any occasional anniversary of the customer. Leave blank if not available.
    </li>
    <li class="list-group-item">
        <strong>Column (cust_gender): </strong> Gender <i class="fa fa-arrow-right"></i> If male type "M", if female type "F", Incase left blank "M" is considered.
    </li>
    <li class="list-group-item">
        <strong>Column (cust_address_1): </strong> Current or permenant address line 1.
    </li>
    <li class="list-group-item">
        <strong>Column (cust_address_2): </strong> Current or permenant address line 2.
    </li>
    <li class="list-group-item">
        <strong>Column (cust_city): </strong> Living city.
    </li>
    <li class="list-group-item">
        <strong>Column (cust_state): </strong> Living state.
    </li>
    <li class="list-group-item">
        <strong>Column (cust_pincode): </strong> Locality pincode.
    </li>
    <li class="list-group-item">
        <strong>Column (cust_country): </strong> Living Country 2 digit code only.
    </li>
    <li class="list-group-item">
        <strong>Column (cust_mobile): </strong> 10 digit contact mobile number
    </li>
    <li class="list-group-item">
        <strong>Column (cust_landline): </strong> Landline number with/without STD code. Max Length - 15 characters.
    </li>
    <li class="list-group-item">
        <strong>Column (cust_email): </strong> An active valid email
    </li>
    <li class="list-group-item">
        <strong>Column (cust_facebook): </strong> Customer facebook Id. Ex: <a href="<?php echo 'https://www.facebook.com/'.$this->session->userdata('pos_hoster_cmp') ?>" target="_blank"><?php echo 'https://www.facebook.com/'.$this->session->userdata('pos_hoster_cmp') ?></a>
    </li>
    <li class="list-group-item">
        <strong>Column (cust_website): </strong> Customer Personal website if available.
    </li>
    <li class="list-group-item">
        <strong>Column (cust_description): </strong> If the above fields are not sufficient, key in a short description about the customer.
    </li>
    <li class="list-group-item">
        <strong>Column (latitude): </strong> Latitudinal locality coordinate of the customer. Ex: 20.593684 (Google maps to address your customer). Leave blank if not required. You can update them later in while viewing customer.
    </li>
    <li class="list-group-item">
        <strong>Column (longitude): </strong> Longitudinal locality coordinate of the customer. Ex: 78.96288000000004. (Google maps to address your customer). Leave blank if not required. You can update them later while viewing customer.
    </li>
    <li class="list-group-item">
        <strong>Column (cust_enable_loyalty): </strong> If you want to enable loyalty for this customer type "1" else "0", incase left blank "1" is considered
    </li>
</ul>
